### ISSUE TITLE
Possible EE and RealPlume incompatibility?

### ISSUE THREAD

**Issue by NoMrBond** [MOARdV/EngineEnhancement#8]
Trying to create a RealPlume config for the KOSMOS nuclear engines, however the exhaust effects for the verniers on the RD-0440 (NTR and LANTR) do not show up, disabling the gimbal/engine hider modules (using !MODULE in an MM config) doesn't/didn't help.  The SmokeScreen report doesn't even list the engine_thrust_small in the available ingame nodes to configure (engine_thrust_small_left/right doesn't work either).
The KOSMOS_RealPlume config is in the KOSMOS DropBox (plugins directory), which I'm assuming you have access too? Otherwise I can supply it.

**Comment by MOARdV** [comment]
I can take a look at it this weekend and see if I can find something.  The gimbal and engine hiders were not particularly good components of that plugin, since they were virtual hacks trying to bend KSP to work with those parts.  I suspect some changes to the model (using common transform names for the Vernier thruster transforms and gimbal transforms, for instance) would have been a better approach, but I'll see if I can get EE working with RealPlume.

**Comment by NoMrBond** [comment]
Had a response from the RealPlume authors and this issue is a module limitation where the same plume type cannot be assigned to different targets within the same config so isn't being cause by EE, sorry for any trouble.
